[theme]
base="light"
backgroundColor="white"
primaryColor="slateBlue"
secondaryBackgroundColor="lavender"
codeBackgroundColor="powderBlue"
baseRadius="full"

[theme.sidebar]
backgroundColor="ghostWhite"
secondaryBackgroundColor="lavender"